delete{
  B(not: [id: {lt: 2}]){
    ti,
    au,
    Turtle(or:[and:[age:{eq:"stari4ok"},age:{eq:101}], name:{eq:True}]){
    },
    Ha(and:[or:[age:{eq:"stari4ok"},age:{eq:101}], name:{eq:True}]){
    },
    Hagehog(and:[age:{eq:"stari4ok"}, not:[and:[or:[age:{eq:"stari4ok"},age:{eq:101}], name:{eq:True}]]]){
    }
  }
}